"use client";
import { useQuery } from "@tanstack/react-query";
import { ArrowLeft } from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { AsyncSkeleton, TerminalError, WorkspaceBoundary } from "../../components/async-state";
import { ProvenanceCard } from "../../components/provenance-card";
import { ReviewActions } from "../../components/review-actions";
import { getCandidate, getEvaluations, queryKeys } from "../../lib/api-client";
export default function ChangeDetailPage() { const params = useParams<{ candidateId: string }>(); return <WorkspaceBoundary>{(workspaceId) => <Candidate workspaceId={workspaceId} candidateId={params.candidateId} />}</WorkspaceBoundary>; }
function Candidate({ workspaceId, candidateId }: { workspaceId: string; candidateId: string }) { const query = useQuery({ queryKey: queryKeys.candidate(workspaceId, candidateId), queryFn: () => getCandidate(candidateId) }); const evaluations = useQuery({ queryKey: queryKeys.evaluations(workspaceId), queryFn: () => getEvaluations() }); if (query.isError) return <TerminalError title="Candidate evidence is unavailable" error={query.error} onRetry={() => query.refetch()} />; if (query.isLoading || !query.data) return <AsyncSkeleton label="Loading candidate evidence" />; const candidate = query.data; const evaluation = candidate.latestEvaluationId ? evaluations.data?.find((item) => item.id === candidate.latestEvaluationId) : evaluations.data?.find((item) => item.candidateId === candidate.id); const blocked = candidate.blockingFindingCount > 0 || candidate.state === "quarantined"; return <><Link href="/changes" className="back-link"><ArrowLeft size={14} />Back to changes</Link><div className="change-hero"><div><div className="change-meta"><span className={`risk-badge ${blocked ? "critical" : "low"}`}>{candidate.trustClass}</span><span>{candidate.namespaceName}</span><span>{candidate.memoryClass}</span></div><h1>{candidate.canonicalText}</h1><p>Candidate {candidate.id} is {candidate.state.replaceAll("_", " ")}.</p></div><div className="change-id"><small>Candidate</small><code>{candidate.id}</code><small>Findings</small><strong>{candidate.findingCount}</strong></div></div><div className="evidence-grid"><ProvenanceCard source={candidate.source.uri} trust={candidate.trustClass} signatureVerified={candidate.source.signatureVerified} digest={candidate.contentDigest} /><section className="evidence-card"><div className="mini-heading">Evidence</div><p>{candidate.blockingFindingCount ? `${candidate.blockingFindingCount} blocking findings were returned.` : "No blocking findings were returned."}</p></section></div><section className="panel findings-panel"><div className="panel-heading"><div><span className="eyebrow">Review evidence</span><h2>{blocked ? "Review blocked" : "Review eligibility"}</h2></div><span className={`state-text ${candidate.state}`}>{candidate.state.replaceAll("_", " ")}</span></div><p>{candidate.findingCount} findings are recorded by the provider. Detailed findings are not exposed by this read contract.</p></section><ReviewActions workspaceId={workspaceId} candidate={candidate} evaluation={evaluation} /></>; }
