"use client";

import { useMutation, useQueryClient } from "@tanstack/react-query";
import { GitCommitHorizontal } from "lucide-react";
import { useRef, useState } from "react";

import type { MemorySummary } from "../../src/contracts/dashboard";
import { queryKeys, rollbackLineage, StashApiError } from "../lib/api-client";
import { retryFingerprint } from "../lib/retry-fingerprint";

export function LineageTimeline({ workspaceId = "legacy", memoryId, lineage }: { workspaceId?: string; memoryId?: string; lineage: MemorySummary[] }) {
  const client = useQueryClient(); const [target, setTarget] = useState<MemorySummary | null>(null); const [confirmation, setConfirmation] = useState(""); const [reason, setReason] = useState(""); const [notice, setNotice] = useState<string | null>(null); const key = useRef<string | null>(null); const fingerprint = useRef<string | null>(null);
  const rollback = useMutation({ mutationFn: () => { const next = retryFingerprint({ lineageId: target!.lineageId, targetVersionId: target!.id, reason }); if (fingerprint.current !== next) { fingerprint.current = next; key.current = null; } return rollbackLineage(target!.lineageId, { targetVersionId: target!.id, reason }, key.current ??= crypto.randomUUID()); }, onSuccess: async (receipt) => { const displayedMemoryId = memoryId ?? target!.id; key.current = null; fingerprint.current = null; setTarget(null); setConfirmation(""); setReason(""); setNotice(`Rollback completed at revision ${receipt.revision}.`); await Promise.all([client.invalidateQueries({ queryKey: queryKeys.memories(workspaceId) }), client.invalidateQueries({ queryKey: queryKeys.memory(workspaceId, displayedMemoryId) }), client.invalidateQueries({ queryKey: queryKeys.audit(workspaceId) }), client.invalidateQueries({ queryKey: queryKeys.overview(workspaceId) })]); }, onError: (error) => setNotice(error instanceof StashApiError ? `${error.message} Request ID: ${error.requestId}. Retry uses the same request key.` : "Rollback failed. Retry uses the same request key.") });
  const selectTarget = (item: MemorySummary) => { key.current = null; setTarget(item); setConfirmation(""); setReason(""); };
  const close = () => { key.current = null; setTarget(null); setConfirmation(""); setReason(""); };
  return <><section className="panel lineage-panel"><div className="panel-heading"><div><span className="eyebrow">Immutable history</span><h2>Lineage timeline</h2></div><span className="tag">{lineage.length} versions</span></div>{notice ? <p role="status">{notice}</p> : null}<ol className="lineage-list">{lineage.map((item) => <li key={item.id}><span className={item.active ? "timeline-dot active" : "timeline-dot"}><GitCommitHorizontal size={13} /></span><div><strong>Version {item.version} {item.active ? <span className="active-pill">Active</span> : null}</strong><p>{item.canonicalText}</p><small>revision {item.revision} · {item.validFrom}</small></div>{!item.active ? <button className="button subtle" onClick={() => selectTarget(item)}>Rollback here</button> : null}</li>)}{!lineage.length ? <li><p><strong>No lineage is available</strong></p><small>History will appear when the provider returns it.</small></li> : null}</ol></section>{target ? <div className="modal-scrim" role="dialog" aria-modal="true"><form className="confirm-dialog" onSubmit={(event) => { event.preventDefault(); if (confirmation === "ROLLBACK" && reason) rollback.mutate(); }}><h3>Rollback to version {target.version}</h3><p>Type ROLLBACK and provide a reason. This creates a new active revision; history remains immutable.</p><label>Confirmation<input aria-label="Rollback confirmation" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></label><label>Reason<input aria-label="Rollback reason" value={reason} onChange={(event) => setReason(event.target.value)} /></label>{rollback.error ? <p role="alert">{notice}</p> : null}<div><button type="button" className="button subtle" onClick={close}>Cancel</button><button className="button danger-button" disabled={confirmation !== "ROLLBACK" || !reason || rollback.isPending}>Rollback</button></div></form></div> : null}</>;
}
