"use client";

import { useMutation, useQueryClient } from "@tanstack/react-query";
import { GitCommitHorizontal } from "lucide-react";
import { useRef, useState } from "react";

import type { MemorySummary } from "../../src/contracts/dashboard";
import { queryKeys, rollbackLineage } from "../lib/api-client";

export function LineageTimeline({ workspaceId = "legacy", lineage }: { workspaceId?: string; lineage: MemorySummary[] }) {
  const client = useQueryClient(); const [target, setTarget] = useState<MemorySummary | null>(null); const [confirmation, setConfirmation] = useState(""); const [reason, setReason] = useState(""); const key = useRef<string | null>(null);
  const rollback = useMutation({ mutationFn: () => rollbackLineage(target!.lineageId, { targetVersionId: target!.id, reason }, key.current ??= crypto.randomUUID()), onSuccess: async () => { const memoryId = target!.id; setTarget(null); setConfirmation(""); setReason(""); await Promise.all([client.invalidateQueries({ queryKey: queryKeys.memories(workspaceId) }), client.invalidateQueries({ queryKey: queryKeys.memory(workspaceId, memoryId) }), client.invalidateQueries({ queryKey: queryKeys.audit(workspaceId) }), client.invalidateQueries({ queryKey: queryKeys.overview(workspaceId) })]); } });
  return <><section className="panel lineage-panel"><div className="panel-heading"><div><span className="eyebrow">Immutable history</span><h2>Lineage timeline</h2></div><span className="tag">{lineage.length} versions</span></div><ol className="lineage-list">{lineage.map((item) => <li key={item.id}><span className={item.active ? "timeline-dot active" : "timeline-dot"}><GitCommitHorizontal size={13} /></span><div><strong>Version {item.version} {item.active ? <span className="active-pill">Active</span> : null}</strong><p>{item.canonicalText}</p><small>revision {item.revision} · {item.validFrom}</small></div>{!item.active ? <button className="button subtle" onClick={() => setTarget(item)}>Rollback here</button> : null}</li>)}{!lineage.length ? <li><p><strong>No lineage is available</strong></p><small>History will appear when the provider returns it.</small></li> : null}</ol></section>{target ? <div className="modal-scrim" role="dialog" aria-modal="true"><form className="confirm-dialog" onSubmit={(event) => { event.preventDefault(); if (confirmation === "ROLLBACK" && reason) rollback.mutate(); }}><h3>Rollback to version {target.version}</h3><p>Type ROLLBACK and provide a reason. This creates a new active revision; history remains immutable.</p><label>Confirmation<input aria-label="Rollback confirmation" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></label><label>Reason<input aria-label="Rollback reason" value={reason} onChange={(event) => setReason(event.target.value)} /></label>{rollback.error ? <p role="alert">Rollback failed. Retry uses the same request key.</p> : null}<div><button type="button" className="button subtle" onClick={() => setTarget(null)}>Cancel</button><button className="button danger-button" disabled={confirmation !== "ROLLBACK" || !reason || rollback.isPending}>Rollback</button></div></form></div> : null}</>;
}
