"use client";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { AsyncSkeleton, TerminalError, WorkspaceBoundary } from "../components/async-state";
import { ChangeQueue } from "../components/change-queue";
import { ProposeMemoryDialog } from "../components/propose-memory-dialog";
import { getCandidates, getWorkspaceStatus, queryKeys } from "../lib/api-client";
export default function ChangesPage() { return <WorkspaceBoundary>{(workspaceId) => <Changes workspaceId={workspaceId} />}</WorkspaceBoundary>; }
function Changes({ workspaceId }: { workspaceId: string }) { const [open, setOpen] = useState(false); const query = useQuery({ queryKey: queryKeys.candidates(workspaceId), queryFn: getCandidates }); const status = useQuery({ queryKey: queryKeys.status(workspaceId), queryFn: getWorkspaceStatus }); if (query.isError) return <TerminalError title="Candidate queue is unavailable" error={query.error} onRetry={() => query.refetch()} />; if (status.isError) return <TerminalError title="Workspace namespaces are unavailable" error={status.error} onRetry={() => status.refetch()} />; if (query.isLoading || status.isLoading || !query.data || !status.data) return <AsyncSkeleton label="Loading candidate queue" />; const namespace = status.data.namespaces[0]; return <><div className="page-header"><div><span className="eyebrow">Release queue</span><h1>Memory changes</h1><p>Review provider-backed provenance and evaluation evidence before activation.</p></div><button className="button secondary" disabled={!namespace} onClick={() => setOpen(true)}>Propose memory</button></div><ChangeQueue candidates={query.data} />{open && namespace ? <ProposeMemoryDialog workspaceId={workspaceId} namespaceId={namespace.id} namespaceName={namespace.name} onClose={() => setOpen(false)} /> : null}</>; }
