import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AppShell } from "./components/app-shell";
import { DataProvider } from "./lib/query-client";
import "./globals.css";

// The CSP nonce is generated by proxy.ts per request, so every route that
// ships client controls must render dynamically and receive that nonce.
export const dynamic = "force-dynamic";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: { default: "Stash", template: "%s · Stash" },
  description: "Release control for production AI-agent memory.",
  metadataBase: new URL("https://trystash.xyz"),
  openGraph: {
    title: "Stash — ship agent memory like code",
    description: "Pull requests, behavioral evaluation, atomic promotion, lineage, and rollback for production agent memory.",
    images: [{ url: "/stash-social-v2.png", width: 1200, height: 630, alt: "Stash release control for production AI-agent memory" }],
  },
  twitter: { card: "summary_large_image", images: ["/stash-social-v2.png"] },
  icons: {
    icon: [
      { url: "/favicon.svg", type: "image/svg+xml" },
      { url: "/favicon-32.png", type: "image/png", sizes: "32x32" },
    ],
    shortcut: "/favicon.svg",
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
};

export const viewport: Viewport = { themeColor: "#100d10" };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DataProvider><AppShell>{children}</AppShell></DataProvider>
      </body>
    </html>
  );
}
