"use client";

import { Cloud, Database, KeyRound, ShieldOff } from "lucide-react";
import { useState } from "react";

export default function SettingsPage() {
  const [confirm, setConfirm] = useState(false); const [message, setMessage] = useState("");
  return <><div className="page-header"><div><span className="eyebrow">Workspace controls</span><h1>Settings</h1><p>Integration metadata is visible. Secret values never are.</p></div></div><div className="settings-grid"><section className="panel settings-panel"><div className="panel-heading"><div><span className="eyebrow">Integrations</span><h2>Provider status</h2></div></div><div className="integration-row"><Database size={16} /><div><strong>CockroachDB Cloud</strong><small>Local verified · cloud endpoint pending</small></div><span className="risk-badge medium">partial</span></div><div className="integration-row"><Cloud size={16} /><div><strong>AWS execution plane</strong><small>No credentials on this machine</small></div><span className="risk-badge medium">pending proof</span></div><div className="integration-row"><KeyRound size={16} /><div><strong>Managed MCP</strong><small>Read-only mode · configuration prepared</small></div><span className="risk-badge low">scoped</span></div></section><section className="panel danger-zone"><div className="panel-heading"><div><span className="eyebrow">Emergency control</span><h2>Freeze promotions</h2></div></div><ShieldOff size={23} /><p>Stops new activation transactions. Active memories and revision-pinned reads remain available.</p><button className="button danger-button" onClick={() => setConfirm(true)}>Freeze promotions</button></section></div>{confirm ? <div className="modal-scrim"><div className="confirm-dialog" role="dialog"><ShieldOff size={22} /><h3>Freeze all promotions?</h3><p>This requires workspace-owner authorization and creates an audit event.</p><div><button className="button secondary" onClick={() => setConfirm(false)}>Cancel</button><button className="button danger-button" onClick={() => { setMessage("Promotion freeze requested"); setConfirm(false); }}>Confirm freeze</button></div></div></div> : null}<span role="status" className="sr-only">{message}</span></>;
}
